
[font]
size = 15.0
normal = { family = "JetBrainsMono NFP", style = "Regular" }

[window]
dimensions = { columns = 130, lines = 30 }
opacity = 0.8
blur = true
title = "Terminal"

[bell]
animation = "Ease"
duration = 1

[keyboard]
bindings = [
  { key = "Right", mods = "Alt", chars = "\u001BF" },
  { key = "Left",  mods = "Alt", chars = "\u001BB" },
]

[general]
import = [
    "~/.config/alacritty/themes/themes/horizon-dark.toml"
]
